# Generated by Django 4.2.6 on 2023-10-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BasicInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("Other", "Other")],
                        max_length=5,
                    ),
                ),
                ("dob", models.CharField(max_length=20)),
                ("age", models.CharField(max_length=2)),
                ("bloodGroup", models.CharField(max_length=3, null=True)),
            ],
        ),
    ]
