# Generated by Django 4.2.6 on 2023-10-15 19:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit_management", "0002_remove_basicinfo_age"),
    ]

    operations = [
        migrations.CreateModel(
            name="studentInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("Other", "Other")],
                        max_length=5,
                    ),
                ),
                ("dob", models.CharField(max_length=20)),
                ("bloodGroup", models.CharField(max_length=3, null=True)),
                ("age", models.CharField(max_length=2)),
                ("studentClass", models.CharField(max_length=2)),
            ],
        ),
        migrations.DeleteModel(
            name="BasicInfo",
        ),
    ]
